repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
        stages: [pre-commit]
      - id: check-docstring-first
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: check-ast
        stages: [pre-commit]
      - id: name-tests-test
        stages: [pre-commit]
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: pylint
        stages: [pre-commit]
        name: pylint
        entry: pylint
        language: python
        types: [python]
